### ISSUE TITLE
cornerstoneTools.js:13678 Uncaught TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by newPeter7** [cornerstonejs/cornerstoneTools#1551]
cornerstoneTools.js:13678 Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at Object.getLabelmaps3D [as labelmaps3D] (cornerstoneTools.js:13678:1)
    at eval (cornerstoneTools.js:6412:1)
    at HTMLDivElement.onImageRendered (cornerstoneTools.js:4106:1)
    at triggerEvent (cornerstone.js:7623:1)
    at eval (cornerstone.js:4304:1)
    at draw (cornerstone.js:2162:1)

**Comment by dicom-chen** [comment]
问题解决了吗，我也遇到了这个问题

**Comment by newPeter7** [comment]
没有哦，虽然看着很难受，不过只是waring，不影响使用。
















在 2023-08-22 15:01:31，"dicom-chen" ***@***.***> 写道：

问题解决了吗，我也遇到了这个问题
